name: Build aleph

on:
  workflow_dispatch: {}
  push:
    paths:
      - aleph/*
      - .github/workflows/aleph.yml

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 3.15.5
          - main
          - develop
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: investigativedata/aleph
          path: aleph/aleph
          ref: ${{ matrix.version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/investigativedata/aleph
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=${{ matrix.version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push release
        uses: docker/build-push-action@v3
        with:
          context: ./aleph
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
